# instead of starting with 0 stitch, this should be a one-time cast-on exception
# follow "turn" through the process and determien where place should end up
# TODO : figure out how to work in the round
#        if "round" join beginning and end of cast-on -- leave room for mobius
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import torch
from torch.autograd import Variable
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import progressbar
import ast

# https://stitch-maps.com/patterns/display/continental-lace/
# stitch_map -- circles with stitch icons indicating what this stitch "is"
# stitches # describe the stitches
# patterns # describe the patterns

# knit # convert a pattern consisting of stitches into a graph. #k2g  # needles
# class edge
# class stitch
# 

# show # lay out the graph generated by "knit" #g2m  # models
# woolygraphs
#   goal : get sauron's southern gaze programmed
#   goal : get northern hemisphere pattern programmed. 

# edge description :
# 1. vertex pair: (i, j)
# 2. edge orientation : "h" or "v"
# 3. bump or keep ("b" or "k")
# 4. edge length : 1 (default)
class edge(object):
  def __init__(self, v, orient, bk, length=1):
    self.v = v
    if (orient not in ["h", "v"]):
      print("Warning : unknown orient (h or v) : {}".format(orient))
    self.orient = orient
    if (bk not in ["b", "k"]):
      print("Warning : unknown bk (bump or keep) : {}".format(bk))
    self.bk = bk
    self.length = length# length

  def print(self):
    print("v: {}, orient : {}, bk : {}, length: {}".format(self.v, self.orient, self.bk, self.length))


# stitch description:
# 1. character  (k or p)
# 2. cursor increment (k : 1) (m1 : 0)
### 2.5 keep : True (default) drop "active" stitch when we're done?
# 3. add : 1 number of stitches to knit into active stitch at cursor position
#          (will bump "active" stitch)
# 4. extra : 0 (stitches to insert AFTER cursor) -- added stitches will be connected horizontally in sequence and all will be connected below -- will NOT bump "active" stitch
# 5. local connections: (we're (0,1) -- ([sts in front of cursor], [sts above active])
#    this list should be sorted ascending -- lowest numbers first (so that edges get added right to left)
#    k : (0, 0, "v", "b") (0, -1, "h", "k")
class stitch_tech(object):
  def __init__(self,
               edge_list,
               character = "k",
               cursor_inc = 0,
               keep = False,
               add = 1,
               extra = 0,
               cursor_dir=False):

    # change direction of cursor?
    # character "k" or "p" or "brp" or "brk"
    self.character = character
    # cursor increment independent from added stitches
    # e.g. for "k" we have 0, for "slip 1", we have 1, for "turn" we have 1
    self.cursor_inc = cursor_inc
    # keep cursor stitch on needle?
    self.keep = keep
    # number of stitches to add INTO cursor stitch (i.e. kfbs)
    self.add = add
    # number of stitches to add AFTER cursor stitch (i.e. yarnovers)
    self.extra = extra
    # e.g. for "k" we have [[-1, 0], [0, -1]] 
    self.edge_list = edge_list
    # change direction of cursor : True or False
    self.cursor_dir = cursor_dir

  def print(self):
    print("character: {}".format(self.character))
    print("cursor_inc: {}".format(self.cursor_inc))
    print("keep: {}".format(self.keep))
    print("add: {}".format(self.add))
    print("extra: {}".format(self.extra))
    print("edge_list: {}".format(self.edge_list))
    print("cursor_dir: {}".format(self.cursor_dir))

class stitch(object):
  def __init__(self, 
               index,
               character = "k",
               behind = [],
               below = []):
    
    # unique index of this stitch
    self.index = index
    # whether this stitch is a knit (k) or purl (p)
    self.character = character
    # list of stitches connected behind this stitch
    self.behind = behind
    # list of stitches connected below this stitch. in order left to right
    # TODO : check that we want to keep universal left and right according to right side
    self.below = below


def edge_make(edges, needles, place, progression, stitches):#, edge):
  #v = edge.v
  sbeh = []
  sbel = []
  skil = []
  edge_list = []

  
  # follow stitches down and to the right to get final position
  for edge in edges:
    pos = place + edge.v[0]*progression
    # if we're working flat at the end of the work, and we're "h", skip.
    if (round == False):
      if (pos >= len(needles)) or (pos < 0):
        continue

    vi = needles[place + edge.v[0]*progression]
    for i in range(edge.v[1]):
      vi = stitches[vi].below[0]
    if edge.orient == "h":
      sbeh.append(vi)
    elif edge.orient == "v":
      sbel.append(vi)

    if edge.bk == "b":
      skil.append(vi)
  return sbeh, sbel, skil, edge_list



# k : character : "k"
#     cursor_inc       : 1

file = open("stitches.txt", "r")
contents = file.read()
sdict = ast.literal_eval(contents)
file.close()

# make dict of string objects...
stitch_techniques = {}
for key in sdict.keys():
  edge_list = []
  for dedge in sdict[key]["edge_list"]:
    edge_list.append(edge(dedge["v"],
                          dedge["orient"],
                          dedge["bk"],
                          dedge["length"]))
  stitch_techniques[key] = stitch_tech(edge_list,
               sdict[key]["character"],
               sdict[key]["cursor_inc"],
               sdict[key]["keep"],
               sdict[key]["add"],
               sdict[key]["extra"],
               sdict[key]["cursor_dir"])


fi = "patterns/garter_4_8_20.txt"
file = open(fi, "r")
contents = file.readlines()
file.close()

# list of stitches
# list of active stitches (ordered)
# cursor position
# edge list

stitches   = [] # list of all stitches
#stitches_c = [] # list of stitch characters
needles    = [] # list of stitches that are being held on the needles
edges = []   # list of connections among stitches
# place always lists the position of the "current" stitch          
place = 0    # start at position after 0th stitch
count = 1
right_side = True # start on right side of work -- cursor going right to left
progression = 1

round = False
# every project starts with a single stitch
stitches.append(stitch(0, "k", [], [])) # 
needles.append(0)

# need stitch object -- each stitch has links to all the stitches below them -- directed graph is top down. 
for line in contents:
  strings = np.array(line.split(" "))
  # remove newlines and blanks
  strings = strings[strings != "\n"]
  strings = strings[strings != ""]
  for s in strings:
    s = s.strip()
    # knit steps:
    # for as many stitches as we have,
    # figure out who is behind us on the needle -- subtract direction from place
    if (s in stitch_techniques):
      stitch_technique = stitch_techniques[s]
    else:
      print(F"ERROR : Unknown stitch {s}, stopping")
      break
    #last = needles[place-progression]
    # add stitches into stitch below AND stitch before
    # loop through edges to figure out where stitches get connected
    # v = []
    # for edge in stitch_technique.edge_list:
    #   # follow edge.v to where we need to go
    #   v.append(edge.v)
    
    #TODO : This needs to come out of the edge loop
    for i in range(stitch_technique.add):
      sbeh, sbel, skil, edges_new = edge_make(stitch_technique.edge_list, needles, place, progression, stitches)
      # also get list of stitches to kill
      stitches.append(stitch(count, stitch_technique.character, sbeh, sbel))
      edges.append(edges_new)
      # bump any finished stitches off the needles
      for vi in skil:
        needles.remove(vi)
        place-=1
      # add the new stitch to the needle
      needles.insert(place, count)#[place] = count


      count += 1
      place += progression

    for i in range(stitch_technique.extra):
      sbeh, sbel, skil, edges_new = edge_make(stitch_technique.edge_list, needles, place, progression, stitches)      
      sbel = []
      skil = []
      stitches.append(stitch(count, stitch_technique.character, sbeh, sbel))
      edges.append(edges_new)
      needles.insert(place+1, count)
      count += 1
      place += progression

    # end by incrementing cursor
    # place += progression*stitch_technique.cursor_inc # this has to add up to all of the count additions above
    # change cursor direction
    right_side = right_side >> stitch_technique.cursor_dir
    progression = 2*right_side - 1
    place += progression*stitch_technique.cursor_inc
  # 0. store "active" stitch
  # 1. label character with stitch character
  # 2. increment cursor by stitch cursor increment
  # 4. for add+extra add stitches create ordered list to insert into active list after cursor
  #    connect first added stitch to all "h" stitches
  #    connect all other stitches to the latest active stitch (a sequence)
  #    connect all added stitches to all "v" stitches
  # 5. bump "b" edges off of active list
  # 6. insert new active stiches after cursor in active list

  # 1. knit -- create new stitch, (replace active stitch with new stitch) advance the cursor by 1, connect [-1, 0] (last active stitch before cursor) and [0, -1] (stitch we just bumped down)
  # coordinates relative to active stitches -- cursor position is 0,0
  #    -- following down (break vertical ties by going right unless specified) is first index
  #    -- following right is negative in first
  # 2. k2tog -- advance the cursor by 2, connect to [-1, 0] and [0, -1], and [1, -1]
  # 3. brioche sl1yo -- 

    
#    print(s)
#m1 : character : "k"
#     cursor inc  : 0
#     add :         0
#     extra :       1
#     local edges : (0,0, "h", "k"), (0, -1, "h", "k"), (1, 0, "h", "v")


#backward loop m1:
#     character : "k"
#     cursor inc  : 0
#     add :         0
#     extra :       1
#     local edges : (0, -1, "h", k")

# kfb : 
#     character : "k"
#     cursor inc  : 1
#     add :         2
#     extra :       0
#     local edges : (0, 0, "v", "b"), (0, -1, "h", "k")
# user-stories
# k
# p
# k2tog
# ssk
# m1
# kfb
# sl1yo
# sl1yo brp
# k5below



# knit steps:
# list of stitches
# list of active stitches (ordered)
# cursor position
# edge list


# 0. store "active" stitch
# 1. label character with stitch character
# 2. increment cursor by stitch cursor increment
# 4. for add+extra add stitches create ordered list to insert into active list after cursor
#    connect first added stitch to all "h" stitches
#    connect all other stitches to the latest active stitch (a sequence)
#    connect all added stitches to all "v" stitches
# 5. bump "b" edges off of active list
# 6. insert new active stiches after cursor in active list

# 1. knit -- create new stitch, (replace active stitch with new stitch) advance the cursor by 1, connect [-1, 0] (last active stitch before cursor) and [0, -1] (stitch we just bumped down)
# coordinates relative to active stitches -- cursor position is 0,0
#    -- following down (break vertical ties by going right unless specified) is first index
#    -- following right is negative in first
# 2. k2tog -- advance the cursor by 2, connect to [-1, 0] and [0, -1], and [1, -1]
# 3. brioche sl1yo -- 


#local_edges = {}
#local_edges["k"] = [[-1, 0], [0, -1]]
#local_edges["p"] = [[-1, 0], [0, -1]]
# always leave cursor on the farthest left of the now-connected nodes?
#local_edges["k2tog"] = [[-1, 0], [0, -1], [1, -1]]
#local_edges["ssk"] = [[-1, 0], [0, -1], [1, -1]]
# do we need to know if edges are up-down versus left-right?

