# index before, between, and after stitches, rather than on stitches. 
# place = 0 -- before any stitches
#0 < place < number of stitches -- between stitches
# place > number of stitches -- after stitches.

# instead of starting with 0 stitch, this should be a one-time cast-on exception
# follow "turn" through the process and determien where place should end up
# TODO : figure out how to work in the round
#        if "round" join beginning and end of cast-on -- leave room for mobius




import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import torch
from torch.autograd import Variable
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import progressbar
import ast
import logging

# https://stitch-maps.com/patterns/display/continental-lace/
# stitch_map -- circles with stitch icons indicating what this stitch "is"
# stitches # describe the stitches
# patterns # describe the patterns

# knit # convert a pattern consisting of stitches into a graph. #k2g  # needles
# class edge
# class stitch
# 

# show # lay out the graph generated by "knit" #g2m  # models
# woolygraphs
#   goal : get sauron's southern gaze programmed
#   goal : get northern hemisphere pattern programmed. 

# edge description :
# 1. vertex pair: (i, j)
# 2. edge orientation : "h" or "v"
# 3. bump or keep ("b" or "k")
# 4. edge length : 1 (default)
class edge(object):
  def __init__(self, v, orient, bk, length=1):
    self.v = v
    if (orient not in ["h", "v"]):
      print("Warning : unknown orient (h or v) : {}".format(orient))
    self.orient = orient
    if (bk not in ["b", "k"]):
      print("Warning : unknown bk (bump or keep) : {}".format(bk))
    self.bk = bk
    self.length = length# length

  def print(self):
    print("v: {}, orient : {}, bk : {}, length: {}".format(self.v, self.orient, self.bk, self.length))


# stitch description:
# 1. character  (k or p)
# 2. cursor increment (k : 1) (m1 : 0)
### 2.5 keep : True (default) drop "active" stitch when we're done?
# 3. add : 1 number of stitches to knit into active stitch at cursor position
#          (will bump "active" stitch)
# 4. extra : 0 (stitches to insert AFTER cursor) -- added stitches will be connected horizontally in sequence and all will be connected below -- will NOT bump "active" stitch
# 5. local connections: (we're (0,1) -- ([sts in front of cursor], [sts above active])
#    this list should be sorted ascending -- lowest numbers first (so that edges get added right to left)
#    k : (0, 0, "v", "b") (0, -1, "h", "k")
class stitch_tech(object):
  def __init__(self,
               character = "k",
               kill = 1,
               add = 1,
               cursor_dir=False):

    # change direction of cursor?
    # character "k" or "p" or "brp" or "brk"
    self.character = character
    # cursor increment independent from added stitches
    # e.g. for "k" we have 0, for "slip 1", we have 1, for "turn" we have 1
    # self.cursor_inc = cursor_inc
    # keep cursor stitch on needle?
    self.kill = kill
    # number of stitches to add INTO cursor stitch (i.e. kfbs)
    self.add = add
    # number of stitches to add AFTER cursor stitch (i.e. yarnovers)
    # self.extra = extra
    # e.g. for "k" we have [[-1, 0], [0, -1]] 
    # self.edge_list = edge_list
    # change direction of cursor : True or False
    self.cursor_dir = cursor_dir

  def print(self):
    print("character: {}".format(self.character))
    print("cursor_inc: {}".format(self.cursor_inc))
    print("keep: {}".format(self.keep))
    print("add: {}".format(self.add))
    print("extra: {}".format(self.extra))
    print("edge_list: {}".format(self.edge_list))
    print("cursor_dir: {}".format(self.cursor_dir))

class stitch(object):
  def __init__(self, 
               index,
               character = "k",
               connected = []):
    
    # unique index of this stitch
    self.index = index
    # whether this stitch is a knit (k) or purl (p)
    self.character = character
    # list of stitches connected to this stitch
    self.connected = connected
    # self.behind = behind
    # # list of stitches connected below this stitch. in order left to right
    # # TODO : check that we want to keep universal left and right according to right side
    # self.below = below


def get_stitch_by_id(work, row_offset, col_offset, curr):
  row = curr[0]+row_offset
  col = curr[1] + col_offset
  if(row < 0 or col < 0):
    return None
  if(len(work) >= row and len(work[row]) >= col):
    print("TRY:", row, col)
    return work[row][col]
  else:
    return None

def edge_make(edges, needles, place, progression, count):#, edge):
  #v = edge.v
  sbeh = []#behind
  sbel = []#below
  skil = []#kill
  edge_list = []
  logging.debug("On the needles: %s", str(needles))
  # follow stitches down and to the right to get final position
  for edge in edges:
    #Add stitch behind
    if edge.orient == 'h':
      if(count - 1 >= 0):
        sbeh.append(count -1)
        edge_list.append((count, count-1))
    #Add stitch below
    elif edge.orient == 'v':
      if(progression > 0):
        stitch_below = needles[place+1]
      else:
        stitch_below = needles[place]
      sbel.append(stitch_below)
      if(stitch_below != count -1):
        edge_list.append((count, stitch_below))
    #Dunno what this does, but it works
    if(progression > 0):
      hi = needles[place + 1 + edge.v[0]]
    else:
      hi = needles[place + edge.v[0]]#needles[place + edge.v[0]*progression]
    if edge.bk == "b":
      skil.append(hi)
  return sbeh, sbel, skil, edge_list

# class project(object):
#   def __init__(self, name):
#     self.name = name
#     self.edges = [] #np.empty((0, 2), dtype=int)
#     self.stitches = [] #np.empty((0, 1), dtype=int)
#     self.edge_list = np.empty((0, 2), dtype=int)
#     self.edge_weights = np.empty((0, 1), dtype=int)

#   def knit(stitch_tech):
  

# k : character : "k"
#     cursor_inc       : 1


"""
Setting up the stitch dictionary

Reads in file (stitches.txt)
"""
file = open("stitches_2.txt", "r")
contents = file.read()
sdict = ast.literal_eval(contents)
file.close()

# make dict of string objects...
stitch_techniques = {}
for key in sdict.keys():
  # edge_list = []
  # for dedge in sdict[key]["edge_list"]:
  #   edge_list.append(edge(dedge["v"],
  #                         dedge["orient"],
  #                         dedge["bk"],
  #                         dedge["length"]))
  stitch_techniques[key] = stitch_tech(
               sdict[key]["character"],
               sdict[key]["kill"],
               sdict[key]["add"],
               sdict[key]["cursor_dir"])



"""
Reading in the stitch file and creating the edge dictionary

"""

fi = "patterns/acorn-3.txt"
pat = fi.split("/")[1]
pat = pat.split(".")[0]#"patterns/small_stockinette.txt"
file = open(fi, "r")
contents = file.readlines()
file.close()

logging.basicConfig(filename='logfile.log', level=logging.DEBUG, force=True)
# list of stitches
# list of active stitches (ordered)
# cursor position
# edge list


#Initializing variables
stitches   = [] # list of all stitches
right_needle  = [] # list of stitches that are being held on the needles
left_needle = []
work = [[]] # list of everything that's been done
edges = []   # list of connections among stitches
# place always lists the position of the "current" stitch  
place = 0    # start at position after 0th stitch  
count = 0    #Number of stitches
current_location = [0,0]  #Where we are currently
right_side = 1 # start on right side of work -- cursor going right to left
progression = 1
row = 0 #Row number that we are on

round = False #We have not made anything in the round work....

edge = True
# every project starts with co values
# stitches.append(stitch(0, "k", [], [])) # 
# needles.append(0)
weight_h = 1
weight_v = 1.5

# need stitch object -- each stitch has links to all the stitches below them -- directed graph is top down. 
for line in contents:
  print("line:", line)
  strings = np.array(line.split(" "))
  # remove newlines and blanks
  strings = strings[strings != "\n"]
  strings = strings[strings != ""]
  st_num = 0
  for s in strings:
    st_num+=1
    s = s.strip()
    # knit steps:
    # for as many stitches as we have,
    # figure out who is behind us on the needle -- subtract direction from place
    logging.debug("Current stitch: %s", str(s))
    if (s in stitch_techniques):
      stitch_technique = stitch_techniques[s]
      if(stitch_technique.cursor_dir):
        tmp = left_needle.copy()
        left_needle = right_needle.copy()
        right_needle = tmp.copy()
        edge = True
      added_st = []
      for a in range(stitch_technique.add):
        right_needle.append(count)
        added_st.append(count)
        if(not edge):
          edges.append([count, count-1, weight_h])
        else:
            edge = False
        count +=1
      for k in range(stitch_technique.kill):
        used_st = left_needle.pop()
        for a in added_st:
          edges.append([used_st, a, weight_v])
      logging.debug("Edges: %s, Stitches: %s", str(edges), str(len(stitches)))
    else:
      #We got a cable people
      #Currently assuming even number for cabling.  I have to remember what the convention is for odd number cables...
      #Is there a convention?  Is this automatable?
      #Also, this does not assume any kind of front/back on the stitches
      if(s[0] == 'c'):
        num = int(s[1:-1])
        held_st = []
        print("COunt before:", count)
        for i in range(int(num/2)):
          held_st.append(left_needle.pop())
        for j in range(int(num/2)):
          right_needle.append(count)
          used_st = left_needle.pop()
          edges.append([used_st, count, weight_v])
          edges.append([count, count-1, weight_h])
          count+=1
        for k in held_st:
          right_needle.append(count)
          edges.append([k, count, weight_v])
          edges.append([count, count-1, weight_h])
          count+=1
        print("count after", count)
        print("CABLE NUM:", num)
      else: 
        print(F"ERROR : Unknown stitch {s}, stopping")
        break

# convert edge list to adjacency matrix
adj = np.matrix(np.zeros((count, count)), dtype=int)
# edges = np.asarray(edges)
# adj[edges[:,0], edges[:,1]] = 1
# adj[edges[:,1], edges[:,0]] = 1
for e in edges:
  adj[e[0], e[1]] = 1

with open(F'dot/{pat}.dot','w') as out:
  out.write("Graph{")
  for e in edges:
    out.write('{} -- {} [weight={}];\n'.format(e[0],e[1],e[2]))
  out.write("}")
    # for line in ('digraph G {','size="16,16";','splines=true;'):
    #     out.write('{}\n'.format(line))  
    # for start,d in nestedg.items():
    #     for end,weight in d.items():
    #           out.write('{} -> {} [ label="{}" ];\n'.format(start,end,weight))
    # out.write('}\n')

df = pd.DataFrame(adj)
fo = F"matrices/{pat}.csv"#"C:/Users/Nexus/Desktop/mobius-python.csv"
df.to_csv(fo)


  # 0. store "active" stitch
  # 1. label character with stitch character
  # 2. increment cursor by stitch cursor increment
  # 4. for add+extra add stitches create ordered list to insert into active list after cursor
  #    connect first added stitch to all "h" stitches
  #    connect all other stitches to the latest active stitch (a sequence)
  #    connect all added stitches to all "v" stitches
  # 5. bump "b" edges off of active list
  # 6. insert new active stiches after cursor in active list

  # 1. knit -- create new stitch, (replace active stitch with new stitch) advance the cursor by 1, connect [-1, 0] (last active stitch before cursor) and [0, -1] (stitch we just bumped down)
  # coordinates relative to active stitches -- cursor position is 0,0
  #    -- following down (break vertical ties by going right unless specified) is first index
  #    -- following right is negative in first
  # 2. k2tog -- advance the cursor by 2, connect to [-1, 0] and [0, -1], and [1, -1]
  # 3. brioche sl1yo -- 

    
#    print(s)
#m1 : character : "k"
#     cursor inc  : 0
#     add :         0
#     extra :       1
#     local edges : (0,0, "h", "k"), (0, -1, "h", "k"), (1, 0, "h", "v")


#backward loop m1:
#     character : "k"
#     cursor inc  : 0
#     add :         0
#     extra :       1
#     local edges : (0, -1, "h", k")

# kfb : 
#     character : "k"
#     cursor inc  : 1
#     add :         2
#     extra :       0
#     local edges : (0, 0, "v", "b"), (0, -1, "h", "k")
# user-stories
# k
# p
# k2tog
# ssk
# m1
# kfb
# sl1yo
# sl1yo brp
# k5below



# knit steps:
# list of stitches
# list of active stitches (ordered)
# cursor position
# edge list


# 0. store "active" stitch
# 1. label character with stitch character
# 2. increment cursor by stitch cursor increment
# 4. for add+extra add stitches create ordered list to insert into active list after cursor
#    connect first added stitch to all "h" stitches
#    connect all other stitches to the latest active stitch (a sequence)
#    connect all added stitches to all "v" stitches
# 5. bump "b" edges off of active list
# 6. insert new active stiches after cursor in active list

# 1. knit -- create new stitch, (replace active stitch with new stitch) advance the cursor by 1, connect [-1, 0] (last active stitch before cursor) and [0, -1] (stitch we just bumped down)
# coordinates relative to active stitches -- cursor position is 0,0
#    -- following down (break vertical ties by going right unless specified) is first index
#    -- following right is negative in first
# 2. k2tog -- advance the cursor by 2, connect to [-1, 0] and [0, -1], and [1, -1]
# 3. brioche sl1yo -- 


#local_edges = {}
#local_edges["k"] = [[-1, 0], [0, -1]]
#local_edges["p"] = [[-1, 0], [0, -1]]
# always leave cursor on the farthest left of the now-connected nodes?
#local_edges["k2tog"] = [[-1, 0], [0, -1], [1, -1]]
#local_edges["ssk"] = [[-1, 0], [0, -1], [1, -1]]
# do we need to know if edges are up-down versus left-right?

