import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import torch
from torch.autograd import Variable
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import progressbar

epsilon = 0.1
HUGE        = 1000000000
TEENY_WEENY = 0.00000001

# TODO :
# 	takes
#		graph file
#	gives
# 		3d plot,
# 		images
# 		new graph file with positions for the vertices. 

# show # lay out the graph generated by "knit" #g2m  # models

# craig's approach
# sum over edges of given object graph
#   minimize curvature
#   (1 - ||v_i - v_j||^2)^2
# sum over paths of length two and take second derivative
# ||v_i - 2v_j + v_k||^2
# universal repulsion
# sum over complete graph
# ||v_i - v_j||^2

# edge length -> 1
# sum((1 - edge length)^2)
# l

widgets = [' Training : ', 
         progressbar.Timer(format= 'elapsed time: %(elapsed)s'), 
         '] ', 
           progressbar.Bar('*'),' (', 
           progressbar.ETA(), ') ', 
          ] 

fi = "circle-python.csv"#"C:/Users/Nexus/Desktop/mobius-python.csv"
fi = "rect-1.csv"
df = pd.read_csv(fi)

# adjacency matrix for pattern
adj = np.matrix(df[df.columns[1:]]).astype(int)

# total number of stitches
sts_tot = adj.shape[0]
#adj[np.tril_indices(sts_tot, 1)] = 0
adj_complete = np.ones([sts_tot, sts_tot])
indices = np.arange(0,sts_tot)
adj_complete[indices, indices] = 0
#adj_complete[np.tril_indices(sts_tot, 1)] = 0

# initialize positions of stitches (vertices)
# all at origin
pos = np.zeros([adj.shape[0], 3])
# all random
pos = np.random.rand(3, adj.shape[0])
# start with a long row
pos = np.zeros([adj.shape[0], 3])
pos[:,0] = np.arange(0,adj.shape[0])
# make sure we aren't colinear
pos[:,1] = np.log(np.arange(0,adj.shape[0])+1)
# make sure we aren't coplanar (not sure we need this?)
pos[:,2] = np.log(np.arange(0,adj.shape[0])+2)

# generate edge list
edg = np.argwhere(adj > 0)
edg_complete = np.argwhere(adj_complete > 0)

epochs_per_stitch = 1000
n_epochs = sts_tot*epochs_per_stitch
max_epochs = n_epochs
bar = progressbar.ProgressBar(max_value=int(n_epochs),  
                              widgets=widgets).start() 

# TODO : noticed that it gets stuck in a tangle, perhaps start with stuff frozen and gradually unfreeze?
# TODO : add one row at a time
# change the spring force to lower(?) order (linear?)
# holy angles batman, maybe minimize l_\infty for centroids rather than l_2
# add inverse square for everything
for epoch in range(n_epochs):
  pos_freeze_ind = int(np.floor(epoch/epochs_per_stitch))+1
  adj_trunc = adj[:pos_freeze_ind, :pos_freeze_ind]
  adj_trunc_complete = np.ones(adj_trunc.shape)
  indices = np.arange(0,adj_trunc.shape[0])
  adj_trunc_complete[indices, indices] = 0


  #edg = np.argwhere(adj_trunc > 0)
  #edg_complete = np.argwhere(adj_trunc_complete > 0)

  epsilon = 0.1 - (0.1*epoch/n_epochs)
  bar.update(epoch)

  # compute force along graph edges
  # create tensor for forces along each edge of the complete graph
  force = np.zeros([adj.shape[0], adj.shape[1], 3])
  # get left and right vertex positions for each edge
  left  = pos[edg[:,0]]
  right = pos[edg[:,1]]
  
  left_complete  = pos[edg_complete[:,0]]
  right_complete = pos[edg_complete[:,1]]
  
  # universal repulsion
  c_repel = .2
  repel_mag = c_repel*(1/np.linalg.norm(right_complete - left_complete, 2, axis=1))
  repel_len = np.linalg.norm(right_complete - left_complete, ord=2, axis=1)
  repel_vec = (repel_mag[:,None]/repel_len[:,None])*(right_complete - left_complete)
  force[edg_complete[:,0], edg_complete[:,1], :] = repel_vec
  
  # graph attraction
  c_attract = .2
  attract_mag = c_attract*np.linalg.norm(right - left, 2, axis=1)
  attract_len = np.linalg.norm(right - left, ord=2, axis=1)
  attract_vec = (attract_mag[:,None]/attract_len[:,None])*(right - left)
  # maybe overwrite repulsion?
  force[edg[:,0], edg[:,1], :] += attract_vec

  force_norm = np.linalg.norm(force)
  print("Epoch : {}/{}, Net Force (Frobenius) : {}".format(epoch+1, n_epochs, force_norm))

  # our gradient will just be the sum of the edge forces
  pos_grad = np.sum(force, axis=1)
  pos = pos+epsilon*pos_grad
  if (epoch%epochs_per_stitch == 0):
    fig = plt.figure()
    ax = plt.axes(projection='3d')
    ax.scatter3D(pos[:,0],
                 pos[:,1],
                 pos[:,2], cmap='Green')
    for edge in edg:
      ax.plot(pos[[edge[0],edge[1]],0],
              pos[[edge[0],edge[1]],1],
              pos[[edge[0],edge[1]],2], c='black', alpha = 0.6)

    plt.show()
